from decimal import Decimal

RULE_SET_ID = "dynamic-energy-calibration"
RULE_SET_VERSION = "1.0"
MIN_WINDOW_DAYS = 21
PREFERRED_MIN_DAYS = 28
PREFERRED_MAX_DAYS = 42
MAX_WINDOW_DAYS = 90
MIN_REPRESENTATIVE_DAYS = 8
MIN_WEEKS = 3
MIN_EDGE_POINTS = 2
ENERGY_EQUIVALENT_LOWER = Decimal("6500")
ENERGY_EQUIVALENT_CENTRAL = Decimal("7700")
ENERGY_EQUIVALENT_UPPER = Decimal("9500")
DEADBAND = Decimal("75")
ABSOLUTE_CAP = Decimal("200")
RELATIVE_CAP = Decimal("0.10")
REDUCED_CAP_MULTIPLIER = Decimal("0.5")
