from decimal import Decimal

RULE_SET_ID = "dynamic-energy-calibration"
RULE_SET_VERSION = "1.0"
MIN_WINDOW_DAYS = 21
PREFERRED_MIN_DAYS = 28
PREFERRED_MAX_DAYS = 42
MAX_WINDOW_DAYS = 90
MIN_REPRESENTATIVE_DAYS = 8
MIN_WEEKS = 3
MIN_EDGE_POINTS = 2
ENERGY_EQUIVALENT_LOWER = Decimal("6500")
ENERGY_EQUIVALENT_CENTRAL = Decimal("7700")
ENERGY_EQUIVALENT_UPPER = Decimal("9500")
DEADBAND = Decimal("75")
ABSOLUTE_CAP = Decimal("200")
RELATIVE_CAP = Decimal("0.10")
REDUCED_CAP_MULTIPLIER = Decimal("0.5")

INTAKE_RULE_SET_VERSION = "intake-informed/1.0"
INTAKE_PREFERRED_MAX_DAYS = 56
MIN_INTAKE_DAYS = 14
MIN_INTAKE_COVERAGE = Decimal("0.70")
MIN_INTAKE_WEEKS = 3
MIN_INTAKE_EDGE_DAYS = 3
MAX_INTAKE_GAP_DAYS = 4
MIN_WEEKEND_DAYS = 2
MIN_WEEKDAY_DAYS = 8
INTAKE_DEADBAND = Decimal("100")
INTAKE_ABSOLUTE_CAP = Decimal("200")
INTAKE_RELATIVE_CAP = Decimal("0.08")
HIGH_REPORTING_ALLOWANCE = Decimal("0.05")
MODERATE_REPORTING_ALLOWANCE = Decimal("0.10")
MINOR_ROUTINE_ALLOWANCE = Decimal("0.03")
CALIBRATION_COOLDOWN_DAYS = 21
MIN_NEW_INTAKE_DAYS = 7
MIN_NEW_WEIGHT_DAYS = 5
MIN_NEW_CALENDAR_SPAN = 14
