"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-28 14:08:35.477171
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_rule_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identifier", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_rule_sets")),
        sa.UniqueConstraint("identifier", "version", name="uq_application_rule_set_version"),
    )
    op.create_table(
        "deletion_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deletion_scope", sa.String(length=48), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_record_count", sa.Integer(), nullable=False),
        sa.Column("confirmation_code", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_records")),
        sa.UniqueConstraint(
            "confirmation_code", name=op.f("uq_deletion_records_confirmation_code")
        ),
    )
    op.create_table(
        "processing_purposes",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description_de", sa.Text(), nullable=False),
        sa.Column(
            "data_categories",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("may_include_special_category_data", sa.Boolean(), nullable=False),
        sa.Column("storage_location", sa.String(length=200), nullable=False),
        sa.Column("retention_period", sa.String(length=200), nullable=False),
        sa.Column("legal_basis_placeholder", sa.String(length=300), nullable=False),
        sa.Column("consent_required", sa.Boolean(), nullable=False),
        sa.Column(
            "recipients_or_processors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("deletion_behavior_de", sa.Text(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("registry_version", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_processing_purposes")),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("physiological_category", sa.String(length=32), nullable=False),
        sa.Column("height_cm", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("current_weight_kg", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("dietary_preference", sa.String(length=32), nullable=False),
        sa.Column("preferred_meals_per_day", sa.Integer(), nullable=True),
        sa.Column("preferred_meal_timing", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "reference_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identifier", sa.String(length=100), nullable=False),
        sa.Column("source_organization", sa.String(length=200), nullable=False),
        sa.Column("edition", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_sets")),
        sa.UniqueConstraint("identifier", "version", name="uq_reference_set_version"),
    )
    op.create_table(
        "activity_profiles",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("occupational_activity_category", sa.String(length=64), nullable=False),
        sa.Column("average_daily_steps", sa.Integer(), nullable=True),
        sa.Column("active_commuting", sa.Boolean(), nullable=False),
        sa.Column("movement_notes", sa.String(length=500), nullable=True),
        sa.Column("manual_pal_override", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_activity_profiles_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_activity_profiles")),
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("client_request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "input_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("supported_scope_status", sa.String(length=32), nullable=False),
        sa.Column("reference_set_id", sa.Uuid(), nullable=False),
        sa.Column("application_rule_set_id", sa.Uuid(), nullable=False),
        sa.Column("reference_set_identifier", sa.String(length=100), nullable=False),
        sa.Column("reference_set_version", sa.String(length=100), nullable=False),
        sa.Column("application_rule_set_identifier", sa.String(length=100), nullable=False),
        sa.Column("application_rule_set_version", sa.String(length=100), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_rule_set_id"],
            ["application_rule_sets.id"],
            name=op.f("fk_assessments_application_rule_set_id_application_rule_sets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_assessments_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reference_set_id"],
            ["reference_sets.id"],
            name=op.f("fk_assessments_reference_set_id_reference_sets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint("profile_id", "client_request_id", name="uq_assessment_client_request"),
    )
    op.create_index(op.f("ix_assessments_profile_id"), "assessments", ["profile_id"], unique=False)
    op.create_table(
        "consent_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("purpose_code", sa.String(length=100), nullable=False),
        sa.Column("consent_text_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_consent_records_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
    )
    op.create_index(
        op.f("ix_consent_records_profile_id"), "consent_records", ["profile_id"], unique=False
    )
    op.create_table(
        "dietary_restrictions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("restriction_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("hard_exclusion", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_dietary_restrictions_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dietary_restrictions")),
    )
    op.create_index(
        op.f("ix_dietary_restrictions_profile_id"),
        "dietary_restrictions",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "health_screenings",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("pregnant", sa.Boolean(), nullable=False),
        sa.Column("breastfeeding", sa.Boolean(), nullable=False),
        sa.Column("diagnosed_eating_disorder", sa.Boolean(), nullable=False),
        sa.Column("diabetes", sa.Boolean(), nullable=False),
        sa.Column("kidney_disease", sa.Boolean(), nullable=False),
        sa.Column("liver_disease", sa.Boolean(), nullable=False),
        sa.Column("medically_prescribed_diet", sa.Boolean(), nullable=False),
        sa.Column("serious_metabolic_condition", sa.Boolean(), nullable=False),
        sa.Column("other_professional_nutrition_condition", sa.Boolean(), nullable=False),
        sa.Column("user_note", sa.Text(), nullable=True),
        sa.Column("screened_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_health_screenings_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_health_screenings")),
    )
    op.create_table(
        "measurements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("measurement_type", sa.String(length=48), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=24), nullable=False),
        sa.Column("measured_at", sa.Date(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_measurements_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurements")),
    )
    op.create_index(
        op.f("ix_measurements_profile_id"), "measurements", ["profile_id"], unique=False
    )
    op.create_table(
        "nutrition_goals",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("goal_type", sa.String(length=48), nullable=False),
        sa.Column("target_weight_kg", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("desired_intensity", sa.String(length=24), nullable=True),
        sa.Column("requested_weekly_rate_kg", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_nutrition_goals_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_nutrition_goals")),
    )
    op.create_table(
        "privacy_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_privacy_actions_profile_id_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_privacy_actions")),
    )
    op.create_index(
        op.f("ix_privacy_actions_profile_id"), "privacy_actions", ["profile_id"], unique=False
    )
    op.create_table(
        "reference_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference_set_id", sa.Uuid(), nullable=False),
        sa.Column("nutrient_code", sa.String(length=64), nullable=False),
        sa.Column("display_name_de", sa.String(length=120), nullable=False),
        sa.Column("physiological_category", sa.String(length=32), nullable=True),
        sa.Column("age_min_years", sa.Integer(), nullable=True),
        sa.Column("age_max_years_exclusive", sa.Integer(), nullable=True),
        sa.Column("pregnancy_state", sa.String(length=24), nullable=False),
        sa.Column("breastfeeding_state", sa.String(length=24), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=5), nullable=True),
        sa.Column("lower_value", sa.Numeric(precision=14, scale=5), nullable=True),
        sa.Column("upper_value", sa.Numeric(precision=14, scale=5), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("reference_value_category", sa.String(length=64), nullable=False),
        sa.Column("source_note", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("superseded_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reference_set_id"],
            ["reference_sets.id"],
            name=op.f("fk_reference_values_reference_set_id_reference_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_values")),
    )
    op.create_index(
        op.f("ix_reference_values_nutrient_code"),
        "reference_values",
        ["nutrient_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_values_reference_set_id"),
        "reference_values",
        ["reference_set_id"],
        unique=False,
    )
    op.create_table(
        "assessment_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("metric_code", sa.String(length=100), nullable=False),
        sa.Column("raw_value", sa.Numeric(precision=30, scale=15), nullable=True),
        sa.Column("display_value", sa.String(length=200), nullable=False),
        sa.Column("lower_value", sa.Numeric(precision=30, scale=15), nullable=True),
        sa.Column("upper_value", sa.Numeric(precision=30, scale=15), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("method_code", sa.String(length=100), nullable=False),
        sa.Column("explanation_de", sa.Text(), nullable=False),
        sa.Column("limitations_de", sa.Text(), nullable=False),
        sa.Column(
            "calculation_inputs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "source_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("application_rule_identifier", sa.String(length=100), nullable=True),
        sa.Column("confidence_type", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_assessment_metrics_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_metrics")),
    )
    op.create_index(
        op.f("ix_assessment_metrics_assessment_id"),
        "assessment_metrics",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_metrics_metric_code"),
        "assessment_metrics",
        ["metric_code"],
        unique=False,
    )
    op.create_table(
        "safety_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("explanation_de", sa.Text(), nullable=False),
        sa.Column("recommended_action_de", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_safety_flags_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safety_flags")),
    )
    op.create_index(
        op.f("ix_safety_flags_assessment_id"), "safety_flags", ["assessment_id"], unique=False
    )
    op.create_table(
        "sport_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_profile_id", sa.Uuid(), nullable=False),
        sa.Column("sport_type", sa.String(length=64), nullable=False),
        sa.Column("sessions_per_week", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("minutes_per_session", sa.Integer(), nullable=False),
        sa.Column("intensity", sa.String(length=24), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_profile_id"],
            ["activity_profiles.profile_id"],
            name=op.f("fk_sport_activities_activity_profile_id_activity_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sport_activities")),
    )
    op.create_index(
        op.f("ix_sport_activities_activity_profile_id"),
        "sport_activities",
        ["activity_profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sport_activities_activity_profile_id"), table_name="sport_activities")
    op.drop_table("sport_activities")
    op.drop_index(op.f("ix_safety_flags_assessment_id"), table_name="safety_flags")
    op.drop_table("safety_flags")
    op.drop_index(op.f("ix_assessment_metrics_metric_code"), table_name="assessment_metrics")
    op.drop_index(op.f("ix_assessment_metrics_assessment_id"), table_name="assessment_metrics")
    op.drop_table("assessment_metrics")
    op.drop_index(op.f("ix_reference_values_reference_set_id"), table_name="reference_values")
    op.drop_index(op.f("ix_reference_values_nutrient_code"), table_name="reference_values")
    op.drop_table("reference_values")
    op.drop_index(op.f("ix_privacy_actions_profile_id"), table_name="privacy_actions")
    op.drop_table("privacy_actions")
    op.drop_table("nutrition_goals")
    op.drop_index(op.f("ix_measurements_profile_id"), table_name="measurements")
    op.drop_table("measurements")
    op.drop_table("health_screenings")
    op.drop_index(op.f("ix_dietary_restrictions_profile_id"), table_name="dietary_restrictions")
    op.drop_table("dietary_restrictions")
    op.drop_index(op.f("ix_consent_records_profile_id"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(op.f("ix_assessments_profile_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_table("activity_profiles")
    op.drop_table("reference_sets")
    op.drop_table("profiles")
    op.drop_table("processing_purposes")
    op.drop_table("deletion_records")
    op.drop_table("application_rule_sets")
    # ### end Alembic commands ###
